/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbtools;

import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.sun.glass.events.KeyEvent;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.server.SeleniumServer;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 *
 * @author wcarrasco
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPublicarAnuncios = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        btAgregarSeccionesPublicarAnuncios = new javax.swing.JButton();
        btIniciarPublicarAnuncios = new javax.swing.JButton();
        tfTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensaje = new javax.swing.JTextArea();
        rbSinREstriccion = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbFechaRestringida = new javax.swing.JRadioButton();
        checkMostrarDesde = new javax.swing.JCheckBox();
        dcFechaMostrarDesde = new datechooser.beans.DateChooserCombo();
        cbHoraMostrarDesde = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        checkMostrarHasta = new javax.swing.JCheckBox();
        dcMostrarHasta = new datechooser.beans.DateChooserCombo();
        cbHoraMostrarHasta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkCopiaCorreo = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTablaSeccionesPublicarAnuncios = new javax.swing.JTable();
        cbDarsedeAlta = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jlImagePath = new javax.swing.JLabel();
        grupoFechaRestringida = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jdCredencialesPublicarAnuncio = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCorreoPublicarAnuncios = new javax.swing.JTextField();
        tfPassCrearAnuncio = new javax.swing.JPasswordField();
        btIniciarCrearAnuncio2 = new javax.swing.JButton();
        cierreActividades = new javax.swing.JDialog();
        btUploadCSV = new javax.swing.JButton();
        tfCACSVName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtCATabla = new javax.swing.JTable();
        cbCAUnenroll = new javax.swing.JCheckBox();
        btCAIniciar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        credencialesCierreActividades = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        tfCACorreo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfCAPass = new javax.swing.JPasswordField();
        btCACredencial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel2.setText("Publicar Anuncios");

        btAgregarSeccionesPublicarAnuncios.setText("Agregar Secciones");
        btAgregarSeccionesPublicarAnuncios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarSeccionesPublicarAnunciosMouseClicked(evt);
            }
        });

        btIniciarPublicarAnuncios.setText("Iniciar");
        btIniciarPublicarAnuncios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciarPublicarAnunciosMouseClicked(evt);
            }
        });

        tfTitulo.setText("Titulo");

        taMensaje.setColumns(20);
        taMensaje.setRows(5);
        jScrollPane1.setViewportView(taMensaje);

        grupoFechaRestringida.add(rbSinREstriccion);
        rbSinREstriccion.setSelected(true);
        rbSinREstriccion.setText("Sin Restricción");
        rbSinREstriccion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbSinREstriccionStateChanged(evt);
            }
        });

        jLabel3.setText("Duración");

        grupoFechaRestringida.add(rbFechaRestringida);
        rbFechaRestringida.setText("Fecha Restringida");
        rbFechaRestringida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaRestringidaActionPerformed(evt);
            }
        });

        checkMostrarDesde.setText("Mostrar desde");
        checkMostrarDesde.setEnabled(false);
        checkMostrarDesde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkMostrarDesdeStateChanged(evt);
            }
        });

        dcFechaMostrarDesde.setEnabled(false);

        cbHoraMostrarDesde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "23:59" }));
        cbHoraMostrarDesde.setEnabled(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbtools/1475621511_access-time.png"))); // NOI18N

        checkMostrarHasta.setText("Mostrar hasta");
        checkMostrarHasta.setEnabled(false);
        checkMostrarHasta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkMostrarHastaStateChanged(evt);
            }
        });

        dcMostrarHasta.setEnabled(false);

        cbHoraMostrarHasta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "23:59" }));
        cbHoraMostrarHasta.setEnabled(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbtools/1475621511_access-time.png"))); // NOI18N

        jLabel6.setText("Enviar a correo");

        checkCopiaCorreo.setText("Enviar una copia de este anuncio al correo de los alumnos");

        jtTablaSeccionesPublicarAnuncios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Seccion", "Realizado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtTablaSeccionesPublicarAnuncios);

        cbDarsedeAlta.setText("Darse de alta del curso después de publicar.");

        jLabel10.setText("Imagen");

        jButton4.setText("Examinar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jlImagePath.setText("Sin Imagen");

        javax.swing.GroupLayout jdPublicarAnunciosLayout = new javax.swing.GroupLayout(jdPublicarAnuncios.getContentPane());
        jdPublicarAnuncios.getContentPane().setLayout(jdPublicarAnunciosLayout);
        jdPublicarAnunciosLayout.setHorizontalGroup(
            jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel2))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btAgregarSeccionesPublicarAnuncios)
                .addGap(141, 141, 141)
                .addComponent(btIniciarPublicarAnuncios, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(24, 24, 24)
                .addComponent(jButton4)
                .addGap(13, 13, 13)
                .addComponent(jlImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(rbSinREstriccion)
                .addGap(18, 18, 18)
                .addComponent(rbFechaRestringida))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(checkMostrarDesde)
                .addGap(18, 18, 18)
                .addComponent(dcFechaMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(cbHoraMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(checkMostrarHasta)
                .addGap(20, 20, 20)
                .addComponent(dcMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(cbHoraMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(checkCopiaCorreo))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(cbDarsedeAlta))
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jdPublicarAnunciosLayout.setVerticalGroup(
            jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAgregarSeccionesPublicarAnuncios)
                    .addComponent(btIniciarPublicarAnuncios))
                .addGap(11, 11, 11)
                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10))
                    .addComponent(jButton4)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jlImagePath)))
                .addGap(8, 8, 8)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(rbSinREstriccion)
                    .addComponent(rbFechaRestringida))
                .addGap(7, 7, 7)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkMostrarDesde)
                    .addComponent(dcFechaMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHoraMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkMostrarHasta)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(dcMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHoraMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)))
                .addGap(33, 33, 33)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(checkCopiaCorreo))
                .addGap(2, 2, 2)
                .addComponent(cbDarsedeAlta)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel7.setText("Credenciales BlackBoard");

        jLabel8.setText("Correo:");

        jLabel9.setText("Contraseña:");

        btIniciarCrearAnuncio2.setText("INICIAR");
        btIniciarCrearAnuncio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciarCrearAnuncio2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jdCredencialesPublicarAnuncioLayout = new javax.swing.GroupLayout(jdCredencialesPublicarAnuncio.getContentPane());
        jdCredencialesPublicarAnuncio.getContentPane().setLayout(jdCredencialesPublicarAnuncioLayout);
        jdCredencialesPublicarAnuncioLayout.setHorizontalGroup(
            jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCredencialesPublicarAnuncioLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(tfCorreoPublicarAnuncios)
                        .addComponent(tfPassCrearAnuncio, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addComponent(btIniciarCrearAnuncio2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jdCredencialesPublicarAnuncioLayout.setVerticalGroup(
            jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCredencialesPublicarAnuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfCorreoPublicarAnuncios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfPassCrearAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btIniciarCrearAnuncio2)
                .addContainerGap())
        );

        btUploadCSV.setText("Upload CSV");
        btUploadCSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUploadCSVMouseClicked(evt);
            }
        });

        tfCACSVName.setEnabled(false);

        jtCATabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Listo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtCATabla);

        cbCAUnenroll.setText("Unenroll");

        btCAIniciar.setText("INICIAR");
        btCAIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCAIniciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cierreActividadesLayout = new javax.swing.GroupLayout(cierreActividades.getContentPane());
        cierreActividades.getContentPane().setLayout(cierreActividadesLayout);
        cierreActividadesLayout.setHorizontalGroup(
            cierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cierreActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(cierreActividadesLayout.createSequentialGroup()
                        .addComponent(btUploadCSV)
                        .addGap(18, 18, 18)
                        .addComponent(tfCACSVName))
                    .addGroup(cierreActividadesLayout.createSequentialGroup()
                        .addComponent(cbCAUnenroll, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCAIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cierreActividadesLayout.setVerticalGroup(
            cierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cierreActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUploadCSV)
                    .addComponent(tfCACSVName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCAUnenroll)
                    .addComponent(btCAIniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton7.setText("jButton7");

        jLabel11.setText("Credenciales");

        jLabel12.setText("Correo:");

        jLabel13.setText("Contraseña:");

        tfCAPass.setText("jPasswordField1");

        btCACredencial.setText("INICIAR");
        btCACredencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCACredencialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout credencialesCierreActividadesLayout = new javax.swing.GroupLayout(credencialesCierreActividades.getContentPane());
        credencialesCierreActividades.getContentPane().setLayout(credencialesCierreActividadesLayout);
        credencialesCierreActividadesLayout.setHorizontalGroup(
            credencialesCierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credencialesCierreActividadesLayout.createSequentialGroup()
                .addGroup(credencialesCierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(credencialesCierreActividadesLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel11))
                    .addGroup(credencialesCierreActividadesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(credencialesCierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(33, 33, 33)
                        .addGroup(credencialesCierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCAPass, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(tfCACorreo)))
                    .addGroup(credencialesCierreActividadesLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btCACredencial)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        credencialesCierreActividadesLayout.setVerticalGroup(
            credencialesCierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credencialesCierreActividadesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addGap(37, 37, 37)
                .addGroup(credencialesCierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCACorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(48, 48, 48)
                .addGroup(credencialesCierreActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfCAPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btCACredencial)
                .addGap(26, 26, 26))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BB TOOLS");

        jButton1.setText("Publicar Anuncios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Enroll / Unenroll");

        jButton3.setText("Descargar Reportes");

        jButton5.setText("Cierre de Actividades");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFechaRestringidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaRestringidaActionPerformed
        if (rbFechaRestringida.isSelected()) {
            checkMostrarDesde.setEnabled(true);
            checkMostrarHasta.setEnabled(true);
        } else if (!rbFechaRestringida.isSelected()) {
            checkMostrarDesde.setEnabled(false);
            checkMostrarHasta.setEnabled(false);
            checkMostrarDesde.setSelected(false);
            checkMostrarHasta.setSelected(false);
        }
    }//GEN-LAST:event_rbFechaRestringidaActionPerformed

    private void rbSinREstriccionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbSinREstriccionStateChanged
        if (!rbSinREstriccion.isSelected()) {
            checkMostrarDesde.setEnabled(true);
            checkMostrarHasta.setEnabled(true);
        } else if (rbSinREstriccion.isSelected()) {
            checkMostrarDesde.setSelected(false);
            checkMostrarHasta.setSelected(false);
            checkMostrarDesde.setEnabled(false);
            checkMostrarHasta.setEnabled(false);
        }
    }//GEN-LAST:event_rbSinREstriccionStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jdPublicarAnuncios.setModal(true);
        jdPublicarAnuncios.pack();
        jdPublicarAnuncios.setLocationRelativeTo(null);
        jdPublicarAnuncios.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void checkMostrarDesdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkMostrarDesdeStateChanged
        if (checkMostrarDesde.isSelected()) {
            dcFechaMostrarDesde.setEnabled(true);
            cbHoraMostrarDesde.setEnabled(true);
        } else if (!checkMostrarDesde.isSelected()) {
            dcFechaMostrarDesde.setEnabled(false);
            cbHoraMostrarDesde.setEnabled(false);
        }
    }//GEN-LAST:event_checkMostrarDesdeStateChanged

    private void checkMostrarHastaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkMostrarHastaStateChanged
        if (checkMostrarHasta.isSelected()) {
            dcMostrarHasta.setEnabled(true);
            cbHoraMostrarHasta.setEnabled(true);
        } else if (!checkMostrarHasta.isSelected()) {
            dcMostrarHasta.setEnabled(false);
            cbHoraMostrarHasta.setEnabled(false);
        }
    }//GEN-LAST:event_checkMostrarHastaStateChanged

    private void btIniciarPublicarAnunciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarPublicarAnunciosMouseClicked
        jdCredencialesPublicarAnuncio.pack();
        jdCredencialesPublicarAnuncio.setModal(true);
        jdCredencialesPublicarAnuncio.setLocationRelativeTo(null);
        jdCredencialesPublicarAnuncio.setVisible(true);
        tfCorreoPublicarAnuncios.setText("lps1.walther.carrasco@laureate.net");
        tfPassCrearAnuncio.setText("Laureate2015$$");
    }//GEN-LAST:event_btIniciarPublicarAnunciosMouseClicked

    
    //CrearAnuncio
    private void btIniciarCrearAnuncio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarCrearAnuncio2MouseClicked
        System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
        WebDriver Driver = new ChromeDriver();

        Driver.get("https://lnps.elearning.laureate.net/");

        //Credenciales
        String correo = tfCorreoPublicarAnuncios.getText();
        String contraseña = tfPassCrearAnuncio.getText();
        //Credenciales

        if (correo.contentEquals("")) {
            correo = "lps1.walther.carrasco@laureate.net";
        }
        if (contraseña.contentEquals("")) {
            contraseña = "Laureate2015$$";
        }

        //Iniciar Sesion
        Driver.findElement(By.id("username")).sendKeys(correo);
        Driver.findElement(By.name("password")).sendKeys(contraseña);
        Driver.findElement(By.id("btnLogin")).click();
        //Iniciar Sesion

        //Ir a system Admi y Cursos
        Driver.findElement(By.id("SystemAdmin.label")).click();
        Driver.findElement(By.id("nav_list_courses")).click();
        //Ir a system Admi y Cursos

        //Seleccionar de ComboBox
        Select select = new Select(Driver.findElement(By.id("courseInfoSearchKeyString")));
        select.selectByValue("CourseId");
        //Seleccionar de ComboBox
        String CourseID = "";
        DefaultTableModel modelo = (DefaultTableModel) jtTablaSeccionesPublicarAnuncios.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            CourseID = (String) modelo.getValueAt(i, 0);
            Driver.findElement(By.id("courseInfoSearchText")).clear();
            Driver.findElement(By.id("courseInfoSearchText")).sendKeys(CourseID);
            Driver.findElement(By.xpath("//*[@value='Go']")).click();

            int index = 1;
            WebElement baseTable = Driver.findElement(By.id("listContainer_datatable"));
            List<WebElement> tableRows = baseTable.findElements(By.tagName("tr"));
            int iteracion = 0;
            //Hace click en el course ID
            Driver.findElement(By.linkText(CourseID)).click();

            //Verificar si esta enrolled o no en el curso
            if (Driver.findElement(By.id("quickEnrollLink")).getText().contentEquals("Inscripción rápida")) {
                System.out.println("ENTRA AL IF");
                Driver.findElement(By.id("quickEnrollLink")).click();
                Driver.switchTo().alert().accept();
            }

            //Hace click en Crear Anuncio
            WebElement myDynamicElement1 = (new WebDriverWait(Driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.id("nav")));
            Driver.findElement(By.id("nav")).click();

            String subject = tfTitulo.getText();
            String body = taMensaje.getText();

            WebElement myDynamicElement = (new WebDriverWait(Driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.id("subject")));

            //Llenando el anuncio
            Driver.findElement(By.name("subject")).sendKeys(subject);
            WebElement myDynamicElement2 = (new WebDriverWait(Driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.id("messagetext_ifr")));
            Driver.findElement(By.id("messagetext_ifr")).sendKeys(taMensaje.getText());

            //Adjuntando imagen
            if (!jlImagePath.getText().contentEquals("Sin Imagen")) {
                try {
                    Robot r = new Robot();
                    Driver.findElement(By.id("messagetext_image")).click();
                    String winHandleBefore = Driver.getWindowHandle();

                    // Perform the click operation that opens new window
                    // Switch to new window opened
                    for (String winHandle : Driver.getWindowHandles()) {
                        Driver.switchTo().window(winHandle);
                    }

                    StringSelection ss = new StringSelection(pathImagen);
                    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);

                    Driver.findElement(By.id("imagepackage_localFileDiv")).click();
                    
                    try {
                        System.out.println("sleep");
                        Thread.sleep(3000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    //r.keyPress(KeyEvent.VK_ENTER);
                    //r.keyRelease(KeyEvent.VK_ENTER);
                    r.keyPress(KeyEvent.VK_CONTROL);
                    r.keyPress(KeyEvent.VK_V);
                    r.keyRelease(KeyEvent.VK_V);
                    r.keyRelease(KeyEvent.VK_CONTROL);
                    r.keyPress(KeyEvent.VK_ENTER);
                    r.keyRelease(KeyEvent.VK_ENTER);
                    try {
                        System.out.println("sleep");
                        Thread.sleep(3000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Driver.findElement(By.id("insert")).click();
                    Driver.switchTo().alert().accept();
                    Driver.switchTo().window(winHandleBefore);
                } catch (AWTException ex) {
                    Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            //Llenando opciones
            if (rbSinREstriccion.isSelected()) {
                Driver.findElement(By.id("isPermanent_true")).click();
            } else if (rbFechaRestringida.isSelected()) {
                if (checkMostrarDesde.isSelected()) {
                    Driver.findElement(By.id("start_restrict")).click();
                    String dia = "", mes = "", ano = "", fecha1 = "";
                    fecha1 = dcFechaMostrarDesde.getText();
                    String[] date = fecha1.split("-");
                    dia = date[0];
                    mes = date[1];
                    ano = "20" + date[2];
                    Driver.findElement(By.id("dp_restrict_start_date")).sendKeys("" + dia + "-" + mes + "-" + ano);
                    Driver.findElement(By.id("tp_restrict_start_time")).sendKeys((String) cbHoraMostrarDesde.getSelectedItem());

                    Driver.findElement(By.id("end_restrict")).click();
                    dia = "";
                    mes = "";
                    ano = "";
                    fecha1 = "";
                    fecha1 = dcMostrarHasta.getText();
                    date = fecha1.split("-");
                    dia = date[0];
                    mes = date[1];
                    ano = "20" + date[2];
                    Driver.findElement(By.id("dp_restrict_end_date")).sendKeys("" + dia + "-" + mes + "-" + ano);
                    Driver.findElement(By.id("tp_restrict_end_time")).sendKeys((String) cbHoraMostrarHasta.getSelectedItem());
                }
            }

            if (checkCopiaCorreo.isSelected()) {
                Driver.findElement(By.id("pushNotify_true")).click();
            }

            //Enviar
            //Driver.findElement(By.name("top_enviar"));
            //Cancelar
            Driver.findElement(By.name("top_Cancelar"));
            modelo.setValueAt(true, i, 1);

            //Unenroll
            if (cbDarsedeAlta.isSelected()) {
                if (Driver.findElement(By.id("quickEnrollLink")).getText().contentEquals("Cancelación de la inscripción rápida")) {
                    System.out.println("ENTRA AL IF");
                    Driver.findElement(By.id("quickEnrollLink")).click();
                    Driver.switchTo().alert().accept();
                }
            }

            //Ir a system Admi y Cursos
            Driver.findElement(By.id("SystemAdmin.label")).click();
            Driver.findElement(By.id("nav_list_courses")).click();
            //Ir a system Admi y Cursos
        }
        System.out.println("LISTO");
        JOptionPane.showMessageDialog(this, "DONE");
    }//GEN-LAST:event_btIniciarCrearAnuncio2MouseClicked

    private void btAgregarSeccionesPublicarAnunciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarSeccionesPublicarAnunciosMouseClicked
        String Sysusername = System.getProperty("user.name");
        JFileChooser jf1 = new JFileChooser("C:\\Users\\" + Sysusername + "\\Documents");
        int entra = jf1.showOpenDialog(null);
        if (entra == JFileChooser.APPROVE_OPTION) {
            File csvAgregarSecciones = jf1.getSelectedFile();
            DefaultTableModel modelo = (DefaultTableModel) jtTablaSeccionesPublicarAnuncios.getModel();
            int rowCount = modelo.getRowCount();

            //Remove rows
            for (int i = rowCount - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            //Remove rows

            //Add rows
            String csvFile = csvAgregarSecciones.getAbsolutePath();
            BufferedReader br = null;
            String line;
            String csvSplitBy = ";";

            try {
                br = new BufferedReader(new FileReader(csvFile));
                while ((line = br.readLine()) != null) {
                    modelo.addRow(new Object[]{line, false});
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                if (br != null) {
                    try {
                        br.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
            System.out.println("CSV LEIDO");
        } else {
            JOptionPane.showMessageDialog(null, "CSV NO ENCONTRADO");
        }
    }//GEN-LAST:event_btAgregarSeccionesPublicarAnunciosMouseClicked

    //Selecciona una imagen
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String Sysusername = System.getProperty("user.name");
        JFileChooser jf1 = new JFileChooser("C:\\Users\\" + Sysusername + "\\Documents");
        int entra = jf1.showOpenDialog(null);
        if (entra == JFileChooser.APPROVE_OPTION) {
            pathImagen = jf1.getSelectedFile().getPath();
            String nombreImagen = jf1.getSelectedFile().getName();
            jlImagePath.setText(nombreImagen);
        } else {
            JOptionPane.showMessageDialog(null, "IMAGEN NO ENCONTRADO");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void btUploadCSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUploadCSVMouseClicked
        JFileChooser jf1 = new JFileChooser("C:\\Users\\Walther\\Documents\\");
        int un = jf1.showOpenDialog(null);
        if (un == JFileChooser.APPROVE_OPTION) {
            File archivo = jf1.getSelectedFile();
            leerArchivo(archivo.getAbsolutePath(), archivo.getName());
        }
    }//GEN-LAST:event_btUploadCSVMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        cierreActividades.setModal(true);
        cierreActividades.pack();
        cierreActividades.setLocationRelativeTo(null);
        cierreActividades.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void btCACredencialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCACredencialMouseClicked
        System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
        WebDriver Driver = new ChromeDriver();

        Driver.get("https://lnps.elearning.laureate.net/");

        //Credenciales
        String correo = tfCACorreo.getText();
        String contraseña = tfCAPass.getText();
        //Credenciales

        if (correo.contentEquals("")) {
            correo = "lps1.walther.carrasco@laureate.net";
        }
        if (contraseña.contentEquals("")) {
            contraseña = "Laureate2015$$";
        }

        //Iniciar Sesion
        Driver.findElement(By.id("username")).sendKeys(correo);
        Driver.findElement(By.name("password")).sendKeys(contraseña);
        Driver.findElement(By.id("btnLogin")).click();
        //Iniciar Sesion

        //Ir a system Admi y Cursos
        Driver.findElement(By.id("SystemAdmin.label")).click();
        Driver.findElement(By.id("nav_list_courses")).click();
        //Ir a system Admi y Cursos

        //Seleccionar de ComboBox
        Select select = new Select(Driver.findElement(By.id("courseInfoSearchKeyString")));
        select.selectByValue("CourseId");
        //Seleccionar de ComboBox
        String CourseID = "";
        DefaultTableModel modelo = (DefaultTableModel) jtCATabla.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            CourseID = (String) modelo.getValueAt(i, 0);
            Driver.findElement(By.id("courseInfoSearchText")).clear();
            Driver.findElement(By.id("courseInfoSearchText")).sendKeys(CourseID);
            Driver.findElement(By.xpath("//*[@value='Go']")).click();

            int index = 1;
            WebElement baseTable = Driver.findElement(By.id("listContainer_datatable"));
            List<WebElement> tableRows = baseTable.findElements(By.tagName("tr"));
            int iteracion = 0;
            //Hace click en el course ID
            Driver.findElement(By.linkText(CourseID)).click();

            //Verificar si esta enrolled o no en el curso
            if (Driver.findElement(By.id("quickEnrollLink")).getText().contentEquals("Inscripción rápida")) {
                System.out.println("ENTRA AL IF");
                Driver.findElement(By.id("quickEnrollLink")).click();
                Driver.switchTo().alert().accept();
            }
            
            
            //Hacer click en la flechita 
            Driver.findElement(By.xpath("//*[@title='Opciones de elemento de menú 1.1 Café del Curso']")).click();
            //Hacer click en la flechita
            
            
            //Hacer click en Cambiar visibilidad del enlace
            WebElement myDynamicElement1 = (new WebDriverWait(Driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@title='Cambiar visibilidad del enlace']")));
            if (!Driver.findElements(By.xpath("//*[@title='Ocultar enlace']")).isEmpty()) {
                System.out.println("No por que ya esta oculto!");
                Driver.findElement(By.xpath("//*[@title='Cambiar visibilidad del enlace']")).click();
            }
            
            //Hacer click en Cambiar visibilidad del enlace
            

            //Ir a system Admi y Cursos
            Driver.findElement(By.id("SystemAdmin.label")).click();
            Driver.findElement(By.id("nav_list_courses")).click();
            //Ir a system Admi y Cursos
        }
        System.out.println("LISTO");
        JOptionPane.showMessageDialog(this, "DONE");
    }//GEN-LAST:event_btCACredencialMouseClicked

    private void btCAIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCAIniciarMouseClicked
        credencialesCierreActividades.setModal(true);
        credencialesCierreActividades.pack();
        credencialesCierreActividades.setLocationRelativeTo(null);
        credencialesCierreActividades.setVisible(true);
    }//GEN-LAST:event_btCAIniciarMouseClicked

    private void leerArchivo(String path, String name){
//        String Sysusername = System.getProperty("user.name");
//        JFileChooser jf1 = new JFileChooser("C:\\Users\\" + Sysusername + "\\Documents");
//        int entra = jf1.showOpenDialog(null);
//        if (entra == JFileChooser.APPROVE_OPTION) {
            File csvAgregarSecciones = new File(path);
            DefaultTableModel modelo = (DefaultTableModel) jtCATabla.getModel();
            int rowCount = modelo.getRowCount();
            tfCACSVName.setText(name);
            //Remove rows
            for (int i = rowCount - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            //Remove rows

            //Add rows
            String csvFile = csvAgregarSecciones.getAbsolutePath();
            BufferedReader br = null;
            String line;
            String csvSplitBy = ";";

            try {
                br = new BufferedReader(new FileReader(csvFile));
                while ((line = br.readLine()) != null) {
                    modelo.addRow(new Object[]{line, "", false});
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                if (br != null) {
                    try {
                        br.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
            System.out.println("CSV LEIDO");
//        } else {
//            JOptionPane.showMessageDialog(null, "CSV NO ENCONTRADO");
//        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarSeccionesPublicarAnuncios;
    private javax.swing.JButton btCACredencial;
    private javax.swing.JButton btCAIniciar;
    private javax.swing.JButton btIniciarCrearAnuncio2;
    private javax.swing.JButton btIniciarPublicarAnuncios;
    private javax.swing.JButton btUploadCSV;
    private javax.swing.JCheckBox cbCAUnenroll;
    private javax.swing.JCheckBox cbDarsedeAlta;
    private javax.swing.JComboBox<String> cbHoraMostrarDesde;
    private javax.swing.JComboBox<String> cbHoraMostrarHasta;
    private javax.swing.JCheckBox checkCopiaCorreo;
    private javax.swing.JCheckBox checkMostrarDesde;
    private javax.swing.JCheckBox checkMostrarHasta;
    private javax.swing.JDialog cierreActividades;
    private javax.swing.JDialog credencialesCierreActividades;
    private datechooser.beans.DateChooserCombo dcFechaMostrarDesde;
    private datechooser.beans.DateChooserCombo dcMostrarHasta;
    private javax.swing.ButtonGroup grupoFechaRestringida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog jdCredencialesPublicarAnuncio;
    private javax.swing.JDialog jdPublicarAnuncios;
    private javax.swing.JLabel jlImagePath;
    private javax.swing.JTable jtCATabla;
    private javax.swing.JTable jtTablaSeccionesPublicarAnuncios;
    private javax.swing.JRadioButton rbFechaRestringida;
    private javax.swing.JRadioButton rbSinREstriccion;
    private javax.swing.JTextArea taMensaje;
    private javax.swing.JTextField tfCACSVName;
    private javax.swing.JTextField tfCACorreo;
    private javax.swing.JPasswordField tfCAPass;
    private javax.swing.JTextField tfCorreoPublicarAnuncios;
    private javax.swing.JPasswordField tfPassCrearAnuncio;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
    String pathImagen = "";
}
