/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbtools;

import com.gargoylesoftware.htmlunit.BrowserVersion;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.server.SeleniumServer;
import org.openqa.selenium.support.ui.Select;

/**
 *
 * @author wcarrasco
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPublicarAnuncios = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        btAgregarSeccionesPublicarAnuncios = new javax.swing.JButton();
        btIniciarPublicarAnuncios = new javax.swing.JButton();
        tfTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rbSinREstriccion = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbFechaRestringida = new javax.swing.JRadioButton();
        checkMostrarDesde = new javax.swing.JCheckBox();
        dcFechaMostrarDesde = new datechooser.beans.DateChooserCombo();
        cbHoraMostrarDesde = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        checkMostrarHasta = new javax.swing.JCheckBox();
        dcMostrarHasta = new datechooser.beans.DateChooserCombo();
        cbHoraMostrarHasta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTablaSeccionesPublicarAnuncios = new javax.swing.JTable();
        grupoFechaRestringida = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jdCredencialesPublicarAnuncio = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCorreoPublicarAnuncios = new javax.swing.JTextField();
        tfPassCrearAnuncio = new javax.swing.JPasswordField();
        btIniciarCrearAnuncio2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel2.setText("Publicar Anuncios");

        btAgregarSeccionesPublicarAnuncios.setText("Agregar Secciones");
        btAgregarSeccionesPublicarAnuncios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarSeccionesPublicarAnunciosMouseClicked(evt);
            }
        });

        btIniciarPublicarAnuncios.setText("Iniciar");
        btIniciarPublicarAnuncios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciarPublicarAnunciosMouseClicked(evt);
            }
        });

        tfTitulo.setText("Titulo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        grupoFechaRestringida.add(rbSinREstriccion);
        rbSinREstriccion.setSelected(true);
        rbSinREstriccion.setText("Sin Restricción");
        rbSinREstriccion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbSinREstriccionStateChanged(evt);
            }
        });

        jLabel3.setText("Duración");

        grupoFechaRestringida.add(rbFechaRestringida);
        rbFechaRestringida.setText("Fecha Restringida");
        rbFechaRestringida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaRestringidaActionPerformed(evt);
            }
        });

        checkMostrarDesde.setText("Mostrar desde");
        checkMostrarDesde.setEnabled(false);
        checkMostrarDesde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkMostrarDesdeStateChanged(evt);
            }
        });

        dcFechaMostrarDesde.setEnabled(false);

        cbHoraMostrarDesde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "23:59" }));
        cbHoraMostrarDesde.setEnabled(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbtools/1475621511_access-time.png"))); // NOI18N

        checkMostrarHasta.setText("Mostrar hasta");
        checkMostrarHasta.setEnabled(false);
        checkMostrarHasta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkMostrarHastaStateChanged(evt);
            }
        });

        dcMostrarHasta.setEnabled(false);

        cbHoraMostrarHasta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "23:59" }));
        cbHoraMostrarHasta.setEnabled(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbtools/1475621511_access-time.png"))); // NOI18N

        jLabel6.setText("Enviar a correo");

        jCheckBox1.setText("Enviar una copia de este anuncio al correo de los alumnos");

        jtTablaSeccionesPublicarAnuncios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Seccion", "Realizado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtTablaSeccionesPublicarAnuncios);

        javax.swing.GroupLayout jdPublicarAnunciosLayout = new javax.swing.GroupLayout(jdPublicarAnuncios.getContentPane());
        jdPublicarAnuncios.getContentPane().setLayout(jdPublicarAnunciosLayout);
        jdPublicarAnunciosLayout.setHorizontalGroup(
            jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTitulo)
                            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                .addComponent(btAgregarSeccionesPublicarAnuncios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btIniciarPublicarAnuncios, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                        .addComponent(rbSinREstriccion)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbFechaRestringida))
                                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                        .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkMostrarDesde)
                                            .addComponent(checkMostrarHasta))
                                        .addGap(18, 18, 18)
                                        .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dcMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dcFechaMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                                .addComponent(cbHoraMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))
                                            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                                .addComponent(cbHoraMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdPublicarAnunciosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(156, 156, 156))
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdPublicarAnunciosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jdPublicarAnunciosLayout.setVerticalGroup(
            jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAgregarSeccionesPublicarAnuncios)
                            .addComponent(btIniciarPublicarAnuncios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(rbSinREstriccion)
                                    .addComponent(rbFechaRestringida))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkMostrarDesde)
                                    .addComponent(dcFechaMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbHoraMostrarDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdPublicarAnunciosLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGap(18, 18, 18)
                        .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkMostrarHasta)
                            .addComponent(dcMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHoraMostrarHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jdPublicarAnunciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel7.setText("Credenciales BlackBoard");

        jLabel8.setText("Correo:");

        jLabel9.setText("Contraseña:");

        btIniciarCrearAnuncio2.setText("INICIAR");
        btIniciarCrearAnuncio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciarCrearAnuncio2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jdCredencialesPublicarAnuncioLayout = new javax.swing.GroupLayout(jdCredencialesPublicarAnuncio.getContentPane());
        jdCredencialesPublicarAnuncio.getContentPane().setLayout(jdCredencialesPublicarAnuncioLayout);
        jdCredencialesPublicarAnuncioLayout.setHorizontalGroup(
            jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCredencialesPublicarAnuncioLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(tfCorreoPublicarAnuncios)
                        .addComponent(tfPassCrearAnuncio, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addComponent(btIniciarCrearAnuncio2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jdCredencialesPublicarAnuncioLayout.setVerticalGroup(
            jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCredencialesPublicarAnuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfCorreoPublicarAnuncios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdCredencialesPublicarAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfPassCrearAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btIniciarCrearAnuncio2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BB TOOLS");

        jButton1.setText("Publicar Anuncios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Enroll / Unenroll");

        jButton3.setText("Descargar Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFechaRestringidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaRestringidaActionPerformed
        if (rbFechaRestringida.isSelected()) {
            checkMostrarDesde.setEnabled(true);
            checkMostrarHasta.setEnabled(true);
        } else if (!rbFechaRestringida.isSelected()) {
            checkMostrarDesde.setEnabled(false);
            checkMostrarHasta.setEnabled(false);
            checkMostrarDesde.setSelected(false);
            checkMostrarHasta.setSelected(false);
        }
    }//GEN-LAST:event_rbFechaRestringidaActionPerformed

    private void rbSinREstriccionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbSinREstriccionStateChanged
        if (!rbSinREstriccion.isSelected()) {
            checkMostrarDesde.setEnabled(true);
            checkMostrarHasta.setEnabled(true);
        } else if (rbSinREstriccion.isSelected()) {
            checkMostrarDesde.setSelected(false);
            checkMostrarHasta.setSelected(false);
            checkMostrarDesde.setEnabled(false);
            checkMostrarHasta.setEnabled(false);
        }
    }//GEN-LAST:event_rbSinREstriccionStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jdPublicarAnuncios.setModal(true);
        jdPublicarAnuncios.pack();
        jdPublicarAnuncios.setLocationRelativeTo(null);
        jdPublicarAnuncios.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void checkMostrarDesdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkMostrarDesdeStateChanged
        if (checkMostrarDesde.isSelected()) {
            dcFechaMostrarDesde.setEnabled(true);
            cbHoraMostrarDesde.setEnabled(true);
        } else if (!checkMostrarDesde.isSelected()) {
            dcFechaMostrarDesde.setEnabled(false);
            cbHoraMostrarDesde.setEnabled(false);
        }
    }//GEN-LAST:event_checkMostrarDesdeStateChanged

    private void checkMostrarHastaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkMostrarHastaStateChanged
        if (checkMostrarHasta.isSelected()) {
            dcMostrarHasta.setEnabled(true);
            cbHoraMostrarHasta.setEnabled(true);
        } else if (!checkMostrarHasta.isSelected()) {
            dcMostrarHasta.setEnabled(false);
            cbHoraMostrarHasta.setEnabled(false);
        }
    }//GEN-LAST:event_checkMostrarHastaStateChanged

    private void btIniciarPublicarAnunciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarPublicarAnunciosMouseClicked
        jdCredencialesPublicarAnuncio.pack();
        jdCredencialesPublicarAnuncio.setModal(true);
        jdCredencialesPublicarAnuncio.setLocationRelativeTo(null);
        jdCredencialesPublicarAnuncio.setVisible(true);
    }//GEN-LAST:event_btIniciarPublicarAnunciosMouseClicked

    private void btIniciarCrearAnuncio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarCrearAnuncio2MouseClicked
        System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
        WebDriver Driver = new ChromeDriver();

        Driver.get("https://lnps.elearning.laureate.net/");

        //Credenciales
        String correo = tfCorreoPublicarAnuncios.getText();
        String contraseña = tfPassCrearAnuncio.getText();
        //Credenciales

        //Iniciar Sesion
        Driver.findElement(By.id("username")).sendKeys(correo);
        Driver.findElement(By.name("password")).sendKeys(contraseña);
        Driver.findElement(By.id("btnLogin")).click();
        //Iniciar Sesion

        //Ir a system Admi y Cursos
        Driver.findElement(By.id("SystemAdmin.label")).click();
        Driver.findElement(By.id("nav_list_courses")).click();
        //Ir a system Admi y Cursos
        
        //Seleccionar de ComboBox
        Select select = new Select(Driver.findElement(By.id("courseInfoSearchKeyString")));
        select.selectByValue("CourseId");
        //Seleccionar de ComboBox
        
        DefaultTableModel modelo = (DefaultTableModel)jtTablaSeccionesPublicarAnuncios.getModel();
        for (int i = 0; i < 1; i++) {
            String CourseID = (String)modelo.getValueAt(i, 0);
            Driver.findElement(By.id("courseInfoSearchText")).sendKeys(CourseID);
            Driver.findElement(By.xpath("//*[@value='Go']")).click();
            
            int index = 1;
            WebElement baseTable = Driver.findElement(By.id("listContainer_datatable"));
            List <WebElement> tableRows = baseTable.findElements(By.tagName("tr"));
            int iteracion = 0;
            for(WebElement trElement : tableRows){
                List <WebElement> tableColumn = trElement.findElements(By.xpath("td"));
                
                System.out.println("# of columns: "+tableColumn.size());
                if (iteracion == 1) {
                    //List <WebElement> elementos = tableColumn.get(2).findElements(By.tagName("a"));
                    //Driver.findElement(By.linkText(CourseID)).click();
                    //tableColumn.get(2).click();
                    System.out.println(tableColumn.get(1).getText());
                    System.out.println(tableColumn.get(1).getAttribute("href"));
                    
                    tableColumn.get(1).click();
                }
                iteracion++;
            }
            //System.out.println("Course ID: "+tableRows.get(index).getText());
            //tableRows.get(index).click();
        }
        System.out.println("LISTO");
    }//GEN-LAST:event_btIniciarCrearAnuncio2MouseClicked

    private void btAgregarSeccionesPublicarAnunciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarSeccionesPublicarAnunciosMouseClicked
        String Sysusername = System.getProperty("user.name");
        JFileChooser jf1 = new JFileChooser("C:\\Users\\" + Sysusername + "\\Documents");
        int entra = jf1.showOpenDialog(null);
        if (entra == JFileChooser.APPROVE_OPTION) {
            File csvAgregarSecciones = jf1.getSelectedFile();
            DefaultTableModel modelo = (DefaultTableModel) jtTablaSeccionesPublicarAnuncios.getModel();
            int rowCount = modelo.getRowCount();

            //Remove rows
            for (int i = rowCount - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            //Remove rows

            //Add rows
            String csvFile = csvAgregarSecciones.getAbsolutePath();
            BufferedReader br = null;
            String line;
            String csvSplitBy = ";";

            try {
                br = new BufferedReader(new FileReader(csvFile));
                while ((line = br.readLine()) != null){                
                    modelo.addRow(new Object[]{line, false});
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                if (br != null) {
                    try {
                        br.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
            System.out.println("CSV LEIDO");
        } else {
            JOptionPane.showMessageDialog(null, "CSV NO ENCONTRADO");
        }
    }//GEN-LAST:event_btAgregarSeccionesPublicarAnunciosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarSeccionesPublicarAnuncios;
    private javax.swing.JButton btIniciarCrearAnuncio2;
    private javax.swing.JButton btIniciarPublicarAnuncios;
    private javax.swing.JComboBox<String> cbHoraMostrarDesde;
    private javax.swing.JComboBox<String> cbHoraMostrarHasta;
    private javax.swing.JCheckBox checkMostrarDesde;
    private javax.swing.JCheckBox checkMostrarHasta;
    private datechooser.beans.DateChooserCombo dcFechaMostrarDesde;
    private datechooser.beans.DateChooserCombo dcMostrarHasta;
    private javax.swing.ButtonGroup grupoFechaRestringida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog jdCredencialesPublicarAnuncio;
    private javax.swing.JDialog jdPublicarAnuncios;
    private javax.swing.JTable jtTablaSeccionesPublicarAnuncios;
    private javax.swing.JRadioButton rbFechaRestringida;
    private javax.swing.JRadioButton rbSinREstriccion;
    private javax.swing.JTextField tfCorreoPublicarAnuncios;
    private javax.swing.JPasswordField tfPassCrearAnuncio;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
